### ISSUE TITLE
.net not working

### ISSUE THREAD

**Issue by NeeteXosu** [Piotrekol/StreamCompanion#296] opened 2021-05-27 13:11 UTC
i have .net installed but streamcompanion tells me that i didnt have it installed

**Comment by omkelderman** [comment] 2021-05-27 13:17
make sure you installed .net5 x86 Desktop Runtime

**Comment by ilsubyeega** [comment] 2021-05-27 13:29
> make sure you installed .net5 x86 Desktop Runtime

duplicate of https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
^, there is x64 and x86 exists at .NET 5, you would need the x86 for one.

**Closed** 2021-05-27 18:54 UTC
Labels: duplicate

**Comment by NeeteXosu** [comment] 2021-05-27 19:35
> make sure you installed .net5 x86 Desktop Runtime

thank you man
