### ISSUE TITLE
!mMod! doesn't update when selecting a mod that can change star rating

### ISSUE THREAD

**Issue by KarBoy2314PL** [Piotrekol/StreamCompanion#133] opened 2020-02-21 15:08 UTC
say a map is 4.51* NoMod, with HR is 4.75* and DT is 6.31* for example

on Song Select, picking whatever mod will still show NoMod rating, despite asking for a modded star rating, however when playing that rating changes accordingly

problem might be the same of #73

**Comment by Piotrekol** [comment] 2020-02-21 19:51
Considering that root cause of both is missing mods data when not playing/spectating, this is indeed duplicate of #73

**Closed by Piotrekol** 2020-02-21 19:51 UTC
