### ISSUE TITLE
Tokens not showing up

### ISSUE THREAD

**Issue by Tycani** [Piotrekol/StreamCompanion#217] opened 2020-10-19 00:17 UTC
hi! I recently installed the program and it writes to text files just fine, but the tokens it uses to represent beatmap information don't show up, including in the text previews, like so https://puu.sh/GEqsp/e74961c873.png -- they don't show up in the Tokens Preview tab either, therefore rendering everything but the pp counter fairly unusable. I'm fairly certain this is a bug, since no settings seem to change this.

**Comment by Piotrekol** [comment] 2020-10-19 19:36
Assuming you attempted this only with the latest version. check if the last version behaves the same for you (uninstall current one first manually) https://github.com/Piotrekol/StreamCompanion/releases/tag/v200926.18

**Comment by Hachi000** [comment] 2020-10-23 02:25
I was having the same problem, going to the previous version fixed it.

**Comment by soarn** [comment] 2020-10-23 20:18
I am also having the same issue, at first I thought it was just unable to hook due to Steam possibly running osu! as admin, but I checked it making sure it wasn't running as admin.  I do get this error if I run the stream companion before starting osu! so it can properly hook:
![image](https://user-images.githubusercontent.com/11000195/97050071-95753780-1531-11eb-9f88-83c1674f62ff.png)

**Comment by lehenbnw** [comment] 2020-10-23 23:12
Same here. After playing around I've discovered there is output from tokens, but for some (like !mapArtistTitle! and !mapDiff!) the output is just blank. It outputs the spaces that I include at the beginning to separate the scroll, but otherwise it seems like that token was just completely deleted. Unstable Rate and live pp/SSPP are fine. I tried reinstalling, re-hooking SC to osu! etc. The only thing that worked was reverting back to the previous version.

**Comment by Piotrekol** [comment] 2020-11-02 20:33
this isn't the same issue, but I managed to reproduce similar behaviour after finishing FirstRun setup [Tokens preview](https://user-images.githubusercontent.com/4990365/97915292-8a9c7d00-1d51-11eb-9da5-414e74f7357d.png). After SC restart it started behaving as expected.
Next release will silently restart SC after finishing FirstRun to work around that issue.

@soarn update ingameOverlay version to get rid of this warning.

As I'm not able to reproduce this exact issue at all, I'll have to ask someone affected to test these releases for this issue: (install & check for the issue)
1a71ed83 https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/35448872/artifacts
5efe7f8d https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/35496837/artifacts
7cae7f7a https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/35684973/artifacts

**Comment by Piotrekol** [comment] 2020-11-14 21:58
Looked at this again and found something in the token format handling code.
I believe that this issue was fixed in the linked build, please retest:
https://ci.appveyor.com/api/buildjobs/j5udf0a6e5t3lnx0/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe

**Comment by Piotrekol** [comment] 2020-11-28 10:08
assuming fixed

**Closed by Piotrekol** 2020-11-28 10:08 UTC
