### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by jjhhgg100123** [Piotrekol/StreamCompanion#164] opened 2020-06-22 06:42 UTC
OS: Windows 10, LTSC
Latest Stream Companion

Whenever I open stream companion (as an admin, or normally) it crashes. There is no error message, however in event viewer I do get a [stack trace](https://paste.gg/p/anonymous/893379c8a5b74998886e785813fa9535).

I've tried reinstalling, and just running the updater in the install folder. [Here](https://paste.gg/p/anonymous/f9ae62f3234f48f88b8d838d84ca1bf7) is my config issue, in case it might be an issue there.

Thanks!

Edit: Figured I should mention that it was fine up until about a week ago. It also worked fine after the recent update, but broke soon after.

**Comment by Piotrekol** [comment] 2020-06-22 08:25
Should be already fixed in the latest prerelease version: https://ci.appveyor.com/api/buildjobs/uu9n5n36cnlon116/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe

**Comment by Piotrekol** [comment] 2020-06-23 06:59
Appeared again in v200621.09(version mentioned above).
I will add additional info to be logged along with this exception later.

**Comment by jjhhgg100123** [comment] 2020-06-24 00:46
Ok, just toss a link when you get around to it if you need me to test the next build.

**Comment by Piotrekol** [comment] 2020-07-17 10:37
Turns out 0f59d48f61448890f2bde9ee15e4710f9b354d46 didn't fix this one. Please reproduce again with build above.

**Comment by jjhhgg100123** [comment] 2020-07-17 19:44
Looks like it's the same error. [Stack Trace](https://paste.gg/p/anonymous/016d7eba87fb4a7184ea9c34f47227d3)

**Comment by Piotrekol** [comment] 2020-07-18 08:06
Retest again with build above. Your error didn't provide LiveVisualizer configuration in sentry as I expected, with means this occurs before any map even gets a chance to get parsed/handled by SC.

**Comment by jjhhgg100123** [comment] 2020-07-18 08:41
Looks like it works now, boots fine and works fine when playing a map.

Thanks!

**Comment by Piotrekol** [comment] 2020-07-18 21:52
That's everything :). I'll push release with this fix in the coming days.

**Closed by Piotrekol** 2020-07-18 21:52 UTC
