### ISSUE TITLE
app crashed after passing certain map

### ISSUE THREAD

**Issue by heyngra** [Piotrekol/StreamCompanion#277] opened 2021-03-28 14:40 UTC
so error happend after I passed hitorigoto on solioquy (replay if it would be possible will be also included). After like half a minute the app crashed itself.
```
AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: Speed)


ArgumentException: An item with the same key has already been added. Key: Speed
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at osu.Game.Rulesets.Osu.Difficulty.OsuPerformanceCalculator.Calculate(Dictionary`2 categoryRatings)
   at PpCalculator.PpCalculator.InternalCalculate(CancellationToken cancellationToken, Nullable`1 endTime, Dictionary`2 categoryAttribs)
   at PpCalculator.PpCalculator.Calculate(CancellationToken cancellationToken, Nullable`1 endTime, Dictionary`2 categoryAttribs)
   at PpCalculator.PpCalculator.Calculate(Nullable`1 endTime, Dictionary`2 categoryAttribs)
   at OsuMemoryEventSource.LivePerformanceCalculator.PPIfBeatmapWouldEndNow()
   at OsuMemoryEventSource.MemoryDataProcessor.<InitLiveTokens>b__48_17()
```
NOTE: was using pre-release [1.0.712](https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/38330173/artifacts).
[heyn - ClariS - Hitorigoto -TV MIX- [Soliloquy] (2021-03-28) Osu.zip](https://github.com/Piotrekol/StreamCompanion/files/6217488/heyn.-.ClariS.-.Hitorigoto.-TV.MIX-.Soliloquy.2021-03-28.Osu.zip)

**Comment by Piotrekol** [comment] 2021-03-28 14:45
This is what 4ea2eef0f9acfc23960b79d6517123f82641b9f1 was supposed to fix(but didn't-wrong root cause). correct fix is included in #278 (only one thread updating live tokens at any given time)

**Closed** 2021-03-30 18:04 UTC
Labels: bug
