### ISSUE TITLE
System.IndexOutOfRangeException on some Mania converts

### ISSUE THREAD

**Issue by NateOnLinux** [Piotrekol/StreamCompanion#377] opened 2023-03-25 00:52 UTC
This doesn't seem to occur for maps made for Mania, just converts. I don't have a large sample of Mania maps to say for sure whether it's exclusive to converts.

Additionally, it only happens for some converts.

Maps I've observed this issue on:
[Hige Driver - Miracle Sugite Yabai (feat. shully) [Insane]](https://osu.ppy.sh/beatmapsets/682290#osu/1442773)
[S3RL - Bass Slut (Original Mix) [All 9 diffs]](https://osu.ppy.sh/beatmapsets/983911#osu/2084862)
[James Portland - Sky [Mao's Normal/NeilPerry's Hard/Nathan's Insane]](https://osu.ppy.sh/beatmapsets/789528#osu/1656877)

Logs:
[2023-03-24.txt](https://github.com/Piotrekol/StreamCompanion/files/11067517/2023-03-24.txt)

Steps to reproduce:
1. Install Stream Companion v230110.18 (currently Latest) from the Releases page
2. Launch Stream Companion and osu!
3. Switch mode from osu! to osu!Mania
4. Select any affected beatmap (Above list is not comprehensive)
5. System.IndexOutOfRangeException - Stream Companion doesn't crash
6. Open "Tokens Preview" while affected beatmap is selected - Stream Companion does crash

**Comment by Piotrekol** [comment] 2023-03-25 05:54
Duplicate of #368

**Closed by Piotrekol** 2023-03-25 05:54 UTC
Labels: duplicate
