### ISSUE TITLE
Add Live Replay Frames as an output Token

### ISSUE THREAD

**Issue by thedarklort** [Piotrekol/StreamCompanion#405] opened 2024-06-22 22:21 UTC
ive already asked that back in 2021 on Discord and then kind of abandoned it

But now that Holdtimes are publicy known im asking again

My goal is to have live Data Visualisation of the current on screen play, either playing or spectating.

Hit distribution works fine but Holdtimes are scuffed because of the polling rate from SC (See [here](https://cdn.discordapp.com/attachments/750160195505619076/1254188109709705306/2024-06-22_23-33-58.mp4?ex=66789533&is=667743b3&hm=22d03f13326586bb2a05c6aceb0c584f859a99a5f448cc279c15a7ff9bdab9b7&))

So is it possible to get the replay data as an output token  so Holdtimes can be calculated correctly?

**Comment by Piotrekol** [comment] 2024-06-23 12:59
Duplicate of #336

**Closed by Piotrekol** 2024-06-23 12:59 UTC
